# Generated by Django 3.0.7 on 2020-06-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0002_usuario_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True),
        ),
    ]
