# Generated by Django 3.0.7 on 2020-06-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0004_administrador_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Administadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelado.Proyecto')),
                ('usuario', models.ManyToManyField(to='Modelado.Usuario')),
            ],
        ),
    ]
