# Generated by Django 3.0.7 on 2020-06-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0005_auto_20200609_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ManyToManyField(to='Modelado.Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='UnirseProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatu', models.CharField(choices=[('Espera', 'Espera'), ('Confirmar', 'Confirmar'), ('Eleminar', 'Eleminar')], max_length=10, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelado.Proyecto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelado.Usuario')),
            ],
        ),
    ]
