# Generated by Django 3.0.7 on 2020-06-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0006_auto_20200609_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='materia',
            field=models.ManyToManyField(to='Modelado.Materias'),
        ),
    ]
