# Generated by Django 3.0.7 on 2020-06-11 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0007_auto_20200609_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unirseproyecto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='EnviarSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agregar_usuario', models.ManyToManyField(blank=True, related_name='is_following', to='Modelado.Usuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Modelado.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('inicio_año', models.IntegerField(blank=True, null=True)),
                ('inicio_mes', models.IntegerField(blank=True, null=True)),
                ('inicio_dia', models.IntegerField(blank=True, null=True)),
                ('inicio_hora', models.IntegerField(blank=True, null=True)),
                ('inicio_min', models.IntegerField(blank=True, null=True)),
                ('escoge_importancia', models.CharField(choices=[('important', 'important'), ('info', 'info')], max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('proyecto', models.ManyToManyField(to='Modelado.Proyecto')),
            ],
        ),
    ]
