# Generated by Django 3.0.7 on 2020-06-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0009_enviarsolicitud_follwers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True),
        ),
    ]
