# Generated by Django 3.0.7 on 2020-06-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0010_auto_20200611_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('even_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
