# Generated by Django 3.0.7 on 2020-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0011_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='escoge_importancia',
            field=models.CharField(choices=[('important', 'important'), ('info', 'info')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='proyecto',
            field=models.ManyToManyField(to='Modelado.Proyecto'),
        ),
    ]
