# Generated by Django 3.0.7 on 2020-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0013_auto_20200611_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='usuario',
            field=models.ManyToManyField(to='Modelado.Usuario'),
        ),
    ]
