# Generated by Django 3.0.7 on 2020-06-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0014_events_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='materia',
            field=models.ManyToManyField(blank=True, to='Modelado.Materias'),
        ),
        migrations.CreateModel(
            name='SolicitudProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatu', models.CharField(choices=[('Espera', 'Espera'), ('Confirmar', 'Confirmar'), ('Eleminar', 'Eleminar')], max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelado.Proyecto')),
                ('usuario', models.ManyToManyField(to='Modelado.Usuario')),
            ],
        ),
    ]
