# Generated by Django 3.0.7 on 2020-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelado', '0015_auto_20200613_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='usuario',
            field=models.ManyToManyField(blank=True, to='Modelado.Usuario'),
        ),
    ]
