# Generated by Django 3.1 on 2020-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Children', 'Children'), ('Parents', 'Parents'), ('GYM', 'GYM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
