# Generated by Django 3.1.3 on 2020-11-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201117_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(max_length=30, verbose_name="person's first name"),
        ),
    ]
